name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run build script
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3.0.1

      - name: Build and push image
        run: gcloud builds submit --tag europe-central2-docker.pkg.dev/notely-474209/notely-ar-repo/notely .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/notely-474209/notely-ar-repo/notely:latest --region europe-central2 --allow-unauthenticated --project notely-474209 --max-instances=4
    